function CoriGrav = myDissipation(in1,in2,in3)
%MYDISSIPATION
%    CORIGRAV = MYDISSIPATION(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    03-Mar-2023 21:14:17

M = in3(:,1);
dq4 = in2(4,:);
g = in3(:,9);
k_ab = in3(:,7);
l_ab = in3(:,6);
m = in3(:,4);
q3 = in1(3,:);
q4 = in1(4,:);
t2 = cos(q4);
t3 = dq4.^2;
CoriGrav = [l_ab.*m.*t2.*t3;M.*g+g.*m+l_ab.*m.*t3.*sin(q4);(k_ab.*(q3.*2.0-q4.*2.0+pi))./2.0;k_ab.*pi.*(-1.0./2.0)-k_ab.*q3+k_ab.*q4-g.*l_ab.*m.*t2];
